input_size: 256
num_latent_layers: 2
latent_layers: [32, 64]
beta: 0.25
batch_size: 512
hidden_units: 128
residual_units: 64
layers: 2
codebook_size: 512
codebook_dim: 64
encoder_conv_filter_size: 3
upsampling_conv_filter_size: 4