input_size: 1024
num_latent_layers: 3
latent_layers: [32, 64, 128]
beta: 0.25
batch_size: 128
hidden_units: 128
residual_units: 64
layers: 2
codebook_size: 512
codebook_dim: 64
encoder_conv_filter_size: 3
upsampling_conv_filter_size: 4